### ISSUE TITLE
15.1.0 fails to build in TypeScript project (15.0.0 works)

### ISSUE THREAD

**Issue by somehan** [contentful/rich-text#252]
Hi,

when upgrading `contentful/rich-text-html-renderer` and `contentful/rich-text-types` from 15.0.0 to 15.1.0, we get the following error: 

`error TS7016: Could not find a declaration file for module '@contentful/rich-text-html-renderer'. '/[path redacted]/node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-renderer.es5.js' implicitly has an 'any' type.`

A minimum sample can be found at https://github.com/somehan/2021-08-cf-lib-issue

Steps to reproduce using the sample project:
* Run `npm i`
* Run `npm run build

Expected behavior:
* No output from `tsc`
* Code gets built without errors

Acctual behavior:
* `tsc` reports one error:
 `error TS7016: Could not find a declaration file for module '@contentful/rich-text-html-renderer'. '/home/[path redacted]/cf-lib-issue/node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-renderer.es5.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/contentful__rich-text-html-renderer` if it exists or add a new declaration (.d.ts) file containing `declare module '@contentful/rich-text-html-renderer';``
  
 When downgrading the libraries to 15.0.0, compilation works as expected.

**Comment by fbaba-nibtravel** [comment]
My team and I are experiencing the same behaviour as described above.

**Comment by somehan** [comment]
ping

**Comment by mbyrne00** [comment]
Still happening in `15.2.0`

**Comment by ClementParis016** [comment]
Maybe this regression has been introduced with [this change](https://github.com/contentful/rich-text/commit/02a4e20efe301af87f883c76f4c12a3d980cdefd#diff-2114d768f6b7e3c783d0f6f838ea3a723791d05ed21afb9c857243f88a7adc44R14)?

**Comment by kamsar** [comment]
Also hit this. The cause is that the `typings` in `package.json` point to `dist/types/index.d.ts`, however this file does not exist in the package: only `dist/types/rich-text-html-renderer/src/index.d.ts` (and strangely `dist/types/rich-text-react-renderer/src/index.d.ts` - not sure why React typings are being published in the non-React package).

As a hacktacular workaround liable to break once this gets fixed, you can do this instead:

```
import { documentToHtmlString } from '@contentful/rich-text-html-renderer/dist/types/rich-text-html-renderer/src/index';
```

**Comment by somehan** [comment]
> Also hit this. The cause is that the `typings` in `package.json` point to `dist/types/index.d.ts`, however this file does not exist in the package: only `dist/types/rich-text-html-renderer/src/index.d.ts` (and strangely `dist/types/rich-text-react-renderer/src/index.d.ts` - not sure why React typings are being published in the non-React package).

@kamsar would it be possible for you to put this into a PR? Maybe that may help getting the issue fixed more easily.

**Comment by djagya** [comment]
Hello @somehan and others, sorry for the inconvenience and your patience. We just released the 15.3.3 version, could you please try to build the project with it? Thank you.

**Comment by mbyrne00** [comment]
@djagya - this release did not fix the problem. Did you test the release on a typescript project? I'm still getting the same issues. Need to stick with `15.0.0` for now :(

```
Could not find a declaration file for module '@contentful/rich-text-html-renderer'. '/path/to/my-project/node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-renderer.es5.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/contentful__rich-text-html-renderer` if it exists or add a new declaration (.d.ts) file containing `declare module '@contentful/rich-text-html-renderer';`  TS7016

  > 1 | import { documentToHtmlString } from '@contentful/rich-text-html-renderer';

````

**Comment by somehan** [comment]
I have updated the code sample at https://github.com/somehan/2021-08-cf-lib-issue. Compilation still fails.

**Comment by somehan** [comment]
@djagya Above you can find a proposal how to possibly fix: https://github.com/contentful/rich-text/issues/252#ref-pullrequest-978579927

**Comment by djagya** [comment]
Ok, thank you for confirming, I'll apply the fix you mentioned.

**Comment by djagya** [comment]
Just released the version v15.3.4 of `rich-text-html-renderer` with the proper fix! Please let me know if it works.

**Comment by somehan** [comment]
I can confirm that my sample does compile with the 15.3.4 :+1:

**Comment by somehan** [comment]
Just for reference: the new version also works in our production app. 
Thanks for the fix, @kamsar and @djagya !

**Comment by SivaGanesh56** [comment]
it is breaking in newer versions
